// src/components/ReviewModal.tsx
import React, { useState, useEffect } from 'react';
import { 
  Shield, 
  CheckCircle2, 
  AlertTriangle, 
  XCircle, 
  X, 
  FileText, 
  User, 
  Tag, 
  MessageSquare,
  Sparkles,
  Loader2
} from 'lucide-react';
import { WorkflowDocument, DocumentStatus, UserPersona } from '../types/workflow';

export type ReviewDecision = 'Approved' | 'ChangesRequested' | 'Rejected';

interface ReviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  document: WorkflowDocument | null;
  currentUser: UserPersona;
  initialDecision?: ReviewDecision;
  onConfirmDecision: (decision: DocumentStatus, reviewNote: string) => Promise<void> | void;
  onShowToast?: (title: string, message: string, type?: 'info' | 'success' | 'warning' | 'error') => void;
}

export const ReviewModal: React.FC<ReviewModalProps> = ({
  isOpen,
  onClose,
  document: doc,
  currentUser,
  initialDecision = 'Approved',
  onConfirmDecision,
  onShowToast
}) => {
  const [selectedDecision, setSelectedDecision] = useState<ReviewDecision>(initialDecision);
  const [feedbackNote, setFeedbackNote] = useState<string>('');
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  useEffect(() => {
    if (initialDecision) {
      setSelectedDecision(initialDecision);
    }
  }, [initialDecision]);

  useEffect(() => {
    if (isOpen && doc) {
      if (selectedDecision === 'Approved') {
        setFeedbackNote('Architecture, security, and compliance requirements verified and approved.');
      } else if (selectedDecision === 'ChangesRequested') {
        setFeedbackNote('Please update the specifications and diagrams in Section 3, then re-upload a new version.');
      } else if (selectedDecision === 'Rejected') {
        setFeedbackNote('Does not comply with enterprise architecture standards.');
      }
    }
  }, [isOpen, selectedDecision, doc]);

  if (!isOpen || !doc) return null;

  const handleSelectDecision = (decision: ReviewDecision) => {
    setSelectedDecision(decision);
    if (decision === 'Approved') {
      setFeedbackNote('Architecture, security, and compliance requirements verified and approved.');
    } else if (decision === 'ChangesRequested') {
      setFeedbackNote('Please update the specifications and diagrams in Section 3, then re-upload a new version.');
    } else if (decision === 'Rejected') {
      setFeedbackNote('Does not comply with enterprise architecture standards.');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if ((selectedDecision === 'ChangesRequested' || selectedDecision === 'Rejected') && !feedbackNote.trim()) {
      if (onShowToast) {
        onShowToast('Feedback Required', `Please provide justification or feedback when selecting "${selectedDecision}".`, 'warning');
      }
      return;
    }

    if (currentUser.role === 'Submitter') {
      if (onShowToast) {
        onShowToast(
          'RBAC Authorization Restricted',
          'Role "Submitter" cannot sign off on reviews. Please switch to a Reviewer or Admin persona.',
          'warning'
        );
      }
      return;
    }

    try {
      setIsSubmitting(true);
      // Execute API service call (using mock endpoint simulation pattern)
      await new Promise(resolve => setTimeout(resolve, 400));
      await onConfirmDecision(selectedDecision as DocumentStatus, feedbackNote.trim());
      
      if (onShowToast) {
        onShowToast(
          'Decision Applied',
          `Document "${doc.title}" successfully transitioned to ${selectedDecision}.`,
          'success'
        );
      }
      onClose();
    } catch (err: any) {
      if (onShowToast) {
        onShowToast('Transition Error', err?.message || 'Failed to submit review decision.', 'error');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div 
        className="bg-[#121216] rounded-2xl max-w-lg w-full p-6 shadow-2xl border border-slate-800 animate-in fade-in zoom-in-95 duration-150 text-slate-200"
        role="dialog"
        aria-modal="true"
        aria-labelledby="review-modal-title"
      >
        {/* Modal Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div className="flex items-center gap-2.5">
            <div className={`w-9 h-9 rounded-xl flex items-center justify-center border ${
              selectedDecision === 'Approved' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' :
              selectedDecision === 'ChangesRequested' ? 'bg-amber-500/10 border-amber-500/20 text-amber-400' :
              'bg-rose-500/10 border-rose-500/20 text-rose-400'
            }`}>
              <Shield className="w-5 h-5" />
            </div>
            <div>
              <h3 id="review-modal-title" className="text-base font-bold text-white">Review Document Decision</h3>
              <p className="text-xs text-slate-400 truncate max-w-xs">{doc.title} (v{doc.versionNumber})</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800/60 transition-all cursor-pointer"
            aria-label="Close review dialog"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Document Quick Metadata Summary */}
        <div className="mt-4 p-3 bg-[#0a0a0c] rounded-xl border border-slate-800/80 grid grid-cols-3 gap-2 text-xs">
          <div>
            <span className="block text-[10px] uppercase font-bold text-slate-500">Submitter</span>
            <span className="font-semibold text-slate-200 truncate block">{doc.submitterName}</span>
          </div>
          <div>
            <span className="block text-[10px] uppercase font-bold text-slate-500">Category</span>
            <span className="font-semibold text-yellow-400">{doc.category}</span>
          </div>
          <div>
            <span className="block text-[10px] uppercase font-bold text-slate-500">Current Status</span>
            <span className="font-semibold text-slate-300">{doc.status}</span>
          </div>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="mt-4 space-y-4">
          {/* Decision Outcome Radio-Button Group */}
          <div>
            <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
              Select Review Outcome *
            </label>
            <div className="grid grid-cols-3 gap-2.5">
              {/* Approve Option */}
              <button
                type="button"
                onClick={() => handleSelectDecision('Approved')}
                className={`p-3 rounded-xl border flex flex-col items-start gap-1.5 transition-all text-left cursor-pointer ${
                  selectedDecision === 'Approved'
                    ? 'bg-emerald-950/40 border-emerald-500 text-white shadow-lg shadow-emerald-950/30'
                    : 'bg-[#0a0a0c] border-slate-800 text-slate-400 hover:border-slate-700 hover:text-slate-200'
                }`}
              >
                <div className="flex items-center justify-between w-full">
                  <CheckCircle2 className={`w-4 h-4 ${selectedDecision === 'Approved' ? 'text-emerald-400' : 'text-slate-500'}`} />
                  {selectedDecision === 'Approved' && <span className="w-2 h-2 rounded-full bg-emerald-400" />}
                </div>
                <div>
                  <span className="block text-xs font-bold text-emerald-300">Approve</span>
                  <span className="text-[10px] text-slate-400 line-clamp-1">Compliant & passed</span>
                </div>
              </button>

              {/* Request Changes Option */}
              <button
                type="button"
                onClick={() => handleSelectDecision('ChangesRequested')}
                className={`p-3 rounded-xl border flex flex-col items-start gap-1.5 transition-all text-left cursor-pointer ${
                  selectedDecision === 'ChangesRequested'
                    ? 'bg-amber-950/40 border-amber-500 text-white shadow-lg shadow-amber-950/30'
                    : 'bg-[#0a0a0c] border-slate-800 text-slate-400 hover:border-slate-700 hover:text-slate-200'
                }`}
              >
                <div className="flex items-center justify-between w-full">
                  <AlertTriangle className={`w-4 h-4 ${selectedDecision === 'ChangesRequested' ? 'text-amber-400' : 'text-slate-500'}`} />
                  {selectedDecision === 'ChangesRequested' && <span className="w-2 h-2 rounded-full bg-amber-400" />}
                </div>
                <div>
                  <span className="block text-xs font-bold text-amber-300">Request Changes</span>
                  <span className="text-[10px] text-slate-400 line-clamp-1">Require v{doc.versionNumber + 1}</span>
                </div>
              </button>

              {/* Reject Option */}
              <button
                type="button"
                onClick={() => handleSelectDecision('Rejected')}
                className={`p-3 rounded-xl border flex flex-col items-start gap-1.5 transition-all text-left cursor-pointer ${
                  selectedDecision === 'Rejected'
                    ? 'bg-rose-950/40 border-rose-500 text-white shadow-lg shadow-rose-950/30'
                    : 'bg-[#0a0a0c] border-slate-800 text-slate-400 hover:border-slate-700 hover:text-slate-200'
                }`}
              >
                <div className="flex items-center justify-between w-full">
                  <XCircle className={`w-4 h-4 ${selectedDecision === 'Rejected' ? 'text-rose-400' : 'text-slate-500'}`} />
                  {selectedDecision === 'Rejected' && <span className="w-2 h-2 rounded-full bg-rose-400" />}
                </div>
                <div>
                  <span className="block text-xs font-bold text-rose-300">Reject</span>
                  <span className="text-[10px] text-slate-400 line-clamp-1">Decline submission</span>
                </div>
              </button>
            </div>
          </div>

          {/* Feedback & Justification Note */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label htmlFor="feedbackNote" className="block text-xs font-bold text-slate-300">
                Reviewer Remarks / Decision Note
                {(selectedDecision === 'ChangesRequested' || selectedDecision === 'Rejected') && (
                  <span className="text-rose-400 ml-1">*</span>
                )}
              </label>
              <span className="text-[11px] text-slate-500">
                {selectedDecision === 'Approved' ? 'Optional sign-off note' : 'Specify required updates'}
              </span>
            </div>
            <textarea
              id="feedbackNote"
              rows={4}
              value={feedbackNote}
              onChange={e => setFeedbackNote(e.target.value)}
              placeholder="Provide architectural feedback or compliance justification..."
              className="w-full px-3.5 py-2.5 text-xs bg-[#0a0a0c] border border-slate-800 rounded-xl text-slate-100 placeholder-slate-500 focus:border-yellow-400 focus:outline-none focus:ring-1 focus:ring-yellow-400"
            />
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-2.5 pt-3 border-t border-slate-800">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="px-4 py-2 text-xs font-semibold text-slate-400 hover:bg-slate-800 rounded-xl transition-all cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className={`px-5 py-2.5 text-xs font-bold text-white rounded-xl shadow-lg transition-all flex items-center gap-2 cursor-pointer ${
                selectedDecision === 'Approved'
                  ? 'bg-emerald-600 hover:bg-emerald-500 shadow-emerald-600/30'
                  : selectedDecision === 'ChangesRequested'
                  ? 'bg-amber-600 hover:bg-amber-500 shadow-amber-600/30'
                  : 'bg-rose-600 hover:bg-rose-500 shadow-rose-600/30'
              }`}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Processing...</span>
                </>
              ) : (
                <span>
                  Confirm {selectedDecision === 'Approved' ? 'Approval' : selectedDecision === 'ChangesRequested' ? 'Change Request' : 'Rejection'}
                </span>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// frontend/src/app/components/review-modal/review-modal.component.ts
import { Component, Input, Output, EventEmitter, inject, signal, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { DocumentItem, DocumentStatus } from '../../models/document.model';
import { DocumentService } from '../../services/document.service';
import { ToastService } from '../../services/toast.service';
import { AuthService } from '../../services/auth.service';

export type ReviewDecisionType = 'Approved' | 'ChangesRequested' | 'Rejected';

@Component({
  selector: 'app-review-modal',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule],
  templateUrl: './review-modal.component.html',
  styleUrls: ['./review-modal.component.scss']
})
export class ReviewModalComponent implements OnChanges {
  @Input() document: DocumentItem | null = null;
  @Input() isOpen = false;
  @Input() initialDecision: ReviewDecisionType = 'Approved';

  @Output() close = new EventEmitter<void>();
  @Output() statusUpdated = new EventEmitter<DocumentItem>();

  private docService = inject(DocumentService);
  private toastService = inject(ToastService);
  public authService = inject(AuthService);
  private fb = inject(FormBuilder);

  public selectedDecision = signal<ReviewDecisionType>('Approved');
  public isSubmitting = signal<boolean>(false);

  public reviewForm = this.fb.group({
    feedbackNote: ['', [Validators.maxLength(1000)]]
  });

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['initialDecision'] && this.initialDecision) {
      this.setDecision(this.initialDecision);
    }
    if (changes['isOpen'] && this.isOpen && this.document) {
      this.populateDefaultNote(this.selectedDecision());
    }
  }

  public setDecision(decision: ReviewDecisionType): void {
    this.selectedDecision.set(decision);
    this.populateDefaultNote(decision);
  }

  private populateDefaultNote(decision: ReviewDecisionType): void {
    const currentVal = this.reviewForm.get('feedbackNote')?.value;
    // Only prefill if empty or previously prefilled
    if (!currentVal || currentVal.startsWith('Architecture') || currentVal.startsWith('Please update') || currentVal.startsWith('Does not comply')) {
      if (decision === 'Approved') {
        this.reviewForm.patchValue({
          feedbackNote: 'Architecture, security, and compliance requirements verified and approved.'
        });
      } else if (decision === 'ChangesRequested') {
        this.reviewForm.patchValue({
          feedbackNote: 'Please update the specifications and diagrams in Section 3, then re-upload a new version.'
        });
      } else if (decision === 'Rejected') {
        this.reviewForm.patchValue({
          feedbackNote: 'Does not comply with enterprise architecture standards.'
        });
      }
    }
  }

  public onCancel(): void {
    this.close.emit();
  }

  public onSubmitReview(): void {
    if (!this.document) return;

    const decision = this.selectedDecision();
    const note = this.reviewForm.get('feedbackNote')?.value?.trim() || '';

    if ((decision === 'ChangesRequested' || decision === 'Rejected') && !note) {
      this.toastService.warning('Feedback Required', `Please provide feedback or justification when selecting "${decision}".`);
      return;
    }

    this.isSubmitting.set(true);
    const targetDoc = this.document;
    const previousStatus = targetDoc.status;
    const reviewerName = this.authService.currentUser()?.fullName || 'Reviewer';

    // API Service Call to execute status transition
    this.docService.updateStatus(targetDoc.id, decision, note).subscribe({
      next: (updatedDoc) => {
        this.isSubmitting.set(false);
        this.toastService.success(
          'Decision Applied',
          `Document "${updatedDoc.title}" marked as ${decision}.`
        );
        this.statusUpdated.emit(updatedDoc);
        this.close.emit();
      },
      error: (err) => {
        // Fallback mock endpoint pattern: simulate client-side transition if backend is offline
        console.warn('[ReviewModal] API call failed, applying mock transition pattern:', err);
        
        const mockUpdatedDoc: DocumentItem = {
          ...targetDoc,
          status: decision as DocumentStatus,
          reviewedAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          assignedReviewerName: reviewerName,
          comments: note ? [
            ...(targetDoc.comments || []),
            {
              id: 'comment-' + Math.random().toString(36).substring(2, 9),
              authorId: this.authService.currentUser()?.id || 'reviewer-id',
              authorName: reviewerName,
              authorRole: this.authService.currentUser()?.role || (this.authService.isReviewer() ? 'Reviewer' as any : 'Admin' as any),
              content: `[Decision: ${decision}] ${note}`,
              isInternalReviewerNote: false,
              createdAt: new Date().toISOString()
            }
          ] : (targetDoc.comments || []),
          auditLogs: [
            {
              id: 'audit-' + Math.random().toString(36).substring(2, 9),
              action: `Status Transition: ${previousStatus} -> ${decision}`,
              performedBy: reviewerName,
              details: note || `Review decision set to ${decision}.`,
              timestamp: new Date().toISOString()
            },
            ...(targetDoc.auditLogs || [])
          ]
        };

        this.isSubmitting.set(false);
        this.toastService.success(
          'Decision Applied (Mock Mode)',
          `Document "${mockUpdatedDoc.title}" marked as ${decision}.`
        );
        this.statusUpdated.emit(mockUpdatedDoc);
        this.close.emit();
      }
    });
  }
}

<div class="modal-backdrop" *ngIf="isOpen" (click)="onCancel()">
  <div class="modal-content" (click)="$event.stopPropagation()">
    <!-- Modal Header -->
    <div class="modal-header">
      <div class="modal-title-wrap">
        <div class="modal-icon" [ngClass]="selectedDecision().toLowerCase()">
          <span *ngIf="selectedDecision() === 'Approved'">✅</span>
          <span *ngIf="selectedDecision() === 'ChangesRequested'">⚠️</span>
          <span *ngIf="selectedDecision() === 'Rejected'">❌</span>
        </div>
        <div>
          <h3>Review Document Decision</h3>
          <span class="modal-subtitle" *ngIf="document">{{ document.title }} (v{{ document.versionNumber }})</span>
        </div>
      </div>
      <button class="close-btn" (click)="onCancel()" title="Close dialog">✕</button>
    </div>

    <!-- Document Info Card -->
    <div class="document-summary-card" *ngIf="document">
      <div class="summary-row">
        <div class="summary-item">
          <span class="meta-label">Submitter</span>
          <strong class="meta-value">{{ document.submitterName }}</strong>
        </div>
        <div class="summary-item">
          <span class="meta-label">Category</span>
          <span class="category-tag">{{ document.category }}</span>
        </div>
        <div class="summary-item">
          <span class="meta-label">Current Status</span>
          <span class="status-tag status-{{ document.status.toLowerCase() }}">{{ document.status }}</span>
        </div>
      </div>
    </div>

    <!-- Review Decision Selection Buttons -->
    <div class="decision-selector-section">
      <label class="section-label">Select Review Outcome *</label>
      <div class="decision-button-grid">
        <!-- Approve Button -->
        <button
          type="button"
          class="decision-choice-btn btn-approve"
          [class.active]="selectedDecision() === 'Approved'"
          (click)="setDecision('Approved')">
          <div class="btn-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="20 6 9 17 4 12"/></svg>
          </div>
          <div class="btn-text-wrap">
            <span class="btn-title">Approve</span>
            <span class="btn-subtitle">Pass architecture & compliance</span>
          </div>
          <div class="selection-check" *ngIf="selectedDecision() === 'Approved'">●</div>
        </button>

        <!-- Request Changes Button -->
        <button
          type="button"
          class="decision-choice-btn btn-changes"
          [class.active]="selectedDecision() === 'ChangesRequested'"
          (click)="setDecision('ChangesRequested')">
          <div class="btn-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67"/></svg>
          </div>
          <div class="btn-text-wrap">
            <span class="btn-title">Request Changes</span>
            <span class="btn-subtitle">Ask submitter to re-upload v{{ document ? document.versionNumber + 1 : 2 }}</span>
          </div>
          <div class="selection-check" *ngIf="selectedDecision() === 'ChangesRequested'">●</div>
        </button>

        <!-- Reject Button -->
        <button
          type="button"
          class="decision-choice-btn btn-reject"
          [class.active]="selectedDecision() === 'Rejected'"
          (click)="setDecision('Rejected')">
          <div class="btn-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
          </div>
          <div class="btn-text-wrap">
            <span class="btn-title">Reject</span>
            <span class="btn-subtitle">Decline submission</span>
          </div>
          <div class="selection-check" *ngIf="selectedDecision() === 'Rejected'">●</div>
        </button>
      </div>
    </div>

    <!-- Reviewer Remarks Form -->
    <form [formGroup]="reviewForm" (ngSubmit)="onSubmitReview()" class="review-form">
      <div class="form-group">
        <div class="label-row">
          <label for="feedbackNote">
            Reviewer Remarks / Feedback Note
            <span *ngIf="selectedDecision() === 'ChangesRequested' || selectedDecision() === 'Rejected'" class="required-star">*</span>
          </label>
          <span class="guidance-hint">
            {{ selectedDecision() === 'Approved' ? 'Optional sign-off remarks' : 'Specify required corrections' }}
          </span>
        </div>
        <textarea
          id="feedbackNote"
          formControlName="feedbackNote"
          rows="4"
          class="form-input"
          placeholder="Enter feedback or architectural justification..."></textarea>
      </div>

      <!-- Modal Action Buttons -->
      <div class="modal-actions">
        <button type="button" class="btn btn-secondary" (click)="onCancel()" [disabled]="isSubmitting()">
          Cancel
        </button>
        <button
          type="submit"
          class="btn btn-primary-decision"
          [ngClass]="'btn-' + selectedDecision().toLowerCase()"
          [disabled]="isSubmitting()">
          <span *ngIf="isSubmitting()" class="spinner-sm"></span>
          <span *ngIf="!isSubmitting()">
            Confirm {{ selectedDecision() === 'Approved' ? 'Approval' : selectedDecision() === 'ChangesRequested' ? 'Change Request' : 'Rejection' }}
          </span>
        </button>
      </div>
    </form>
  </div>
</div>
